### ISSUE TITLE
AngularJS and SEO

### ISSUE THREAD

**Issue by abey-alex** [mahesmohan/auragemedia#1]
To have optimal SEO, you might need to configure the server routes.

More at : http://www.yearofmoo.com/2012/11/angularjs-and-seo.html

This needs to be taken care.

**Comment by mahesmohan** [comment]
Will look into it asap.

**Comment by mahesmohan** [comment]
Currently the site is not using angular and coming to the SEO part the site isn't quite presentable to the clientele of the organisation with this content.
Maximum SEO needs to be done and I have asked the team to send me better content.
